#!/usr/bin/env bash
# First-run setup for the local Airflow (called by `make airflow-up`; safe to run again).
#
# Writes, only if missing, two gitignored files next to docker-compose.yaml:
#   .env                                          compose variables: host UID, Postgres password,
#                                                 JWT secret, Fernet key (random, local only)
#   .secrets/simple_auth_manager_passwords.json   the Airflow login: user admin, a random password
# The password is printed once, when it is generated. Later it is only in that file.
#
# It also checks that the application-default credentials file exists, since compose mounts it
# read-only into the containers (the file itself is never copied).

set -euo pipefail

here="$(cd "$(dirname "$0")/.." && pwd)"
env_file="$here/.env"
secrets_dir="$here/.secrets"
passwords_file="$secrets_dir/simple_auth_manager_passwords.json"
adc_file="${GCP_ADC_FILE:-$HOME/.config/gcloud/application_default_credentials.json}"

random_hex() { openssl rand -hex "$1"; }

mkdir -p "$here/logs"

if [[ ! -f "$env_file" ]]; then
  umask 077
  {
    echo "# Generated by scripts/init-secrets.sh for the local Airflow. Gitignored; do not commit."
    echo "AIRFLOW_UID=$(id -u)"
    echo "AIRFLOW_POSTGRES_PASSWORD=$(random_hex 24)"
    echo "AIRFLOW_JWT_SECRET=$(random_hex 32)"
    # A Fernet key is 32 random bytes, URL-safe base64.
    echo "AIRFLOW_FERNET_KEY=$(openssl rand -base64 32 | tr '+/' '-_')"
  } > "$env_file"
  echo "wrote airflow/.env (compose variables; generated, gitignored)"
fi

if [[ ! -f "$passwords_file" ]]; then
  umask 077
  mkdir -p "$secrets_dir"
  password="$(openssl rand -base64 18 | tr -d '/+=' | cut -c1-20)"
  printf '{"admin": "%s"}\n' "$password" > "$passwords_file"
  echo
  echo "Airflow login (shown once): user admin, password $password"
  echo "Saved in airflow/.secrets/simple_auth_manager_passwords.json (gitignored)."
  echo
fi

if [[ ! -f "$adc_file" ]]; then
  echo "no application-default credentials at $adc_file" >&2
  echo "run: gcloud auth application-default login   (or set GCP_ADC_FILE)" >&2
  exit 2
fi
