-- @table Campaign performance by day: one row per date x source x session source / medium /
--     campaign. Sessions, orders and revenue come from fct_sessions (an order counts on its
--     session's date and campaign; a purchase with no transaction_id and no revenue is not an
--     order; an order in no session, a cookieless purchase, is only in fct_orders). Cost comes from tagline_raw.campaign_costs, which is
--     SYNTHETIC (seeded, generated by tagline/pipeline, not real spend), restricted to the dates
--     each source has sessions for. A cost row with no sessions still appears (spend, no visits);
--     cost_usd is NULL where no spend is recorded (organic, referral, direct, obfuscated rows).
--     Built by tagline/pipeline.
-- @column date: Session date (property time zone).
-- @column source: ga4_sample or tagline_site.
-- @column session_source: fct_sessions.session_source.
-- @column session_medium: fct_sessions.session_medium.
-- @column session_campaign: fct_sessions.session_campaign.
-- @column sessions: Sessions.
-- @column engaged_sessions: Engaged sessions.
-- @column orders: Orders placed in those sessions (fct_sessions.orders: after the transaction_id dedupe, zero-value
--     purchases without a transaction_id not counted).
-- @column revenue_usd: Revenue of those orders.
-- @column cost_usd: SYNTHETIC ad spend for the day from campaign_costs; NULL when none is recorded.
-- @column roas: revenue_usd / cost_usd (NULL without cost).
-- @column cost_per_order: cost_usd / orders (NULL without cost or orders).

CREATE OR REPLACE TABLE `{{ project }}.{{ marts }}.mart_campaign_daily`
PARTITION BY date
AS
WITH sessions AS (
  SELECT
    session_date AS date,
    source,
    session_source,
    session_medium,
    session_campaign,
    COUNT(*) AS sessions,
    COUNTIF(is_engaged) AS engaged_sessions,
    SUM(orders) AS orders,
    -- Money is summed as NUMERIC (exact decimals) and turned back into FLOAT64, so a total does not depend on the
    -- order BigQuery adds the rows in: as FLOAT64, one row's revenue came out as 278.96 in one build and
    -- 278.96000000000004 in another (Stage 4).
    COALESCE(CAST(SUM(CAST(revenue_usd AS NUMERIC)) AS FLOAT64), 0) AS revenue_usd
  FROM `{{ project }}.{{ marts }}.fct_sessions`
  GROUP BY date, source, session_source, session_medium, session_campaign
),

covered AS (
  SELECT source, MIN(session_date) AS first_date, MAX(session_date) AS last_date
  FROM `{{ project }}.{{ marts }}.fct_sessions`
  GROUP BY source
),

costs AS (
  SELECT
    c.cost_date AS date,
    c.source,
    c.session_source,
    c.session_medium,
    c.session_campaign,
    CAST(SUM(CAST(c.cost_usd AS NUMERIC)) AS FLOAT64) AS cost_usd
  FROM `{{ project }}.{{ raw }}.campaign_costs` AS c
  JOIN covered AS v
    ON v.source = c.source AND c.cost_date BETWEEN v.first_date AND v.last_date
  GROUP BY date, source, session_source, session_medium, session_campaign
)

SELECT
  date,
  source,
  session_source,
  session_medium,
  session_campaign,
  COALESCE(s.sessions, 0) AS sessions,
  COALESCE(s.engaged_sessions, 0) AS engaged_sessions,
  COALESCE(s.orders, 0) AS orders,
  COALESCE(s.revenue_usd, 0) AS revenue_usd,
  c.cost_usd,
  ROUND(SAFE_DIVIDE(COALESCE(s.revenue_usd, 0), c.cost_usd), 4) AS roas,
  ROUND(SAFE_DIVIDE(c.cost_usd, NULLIF(s.orders, 0)), 2) AS cost_per_order
FROM sessions AS s
FULL OUTER JOIN costs AS c
  USING (date, source, session_source, session_medium, session_campaign)
