"""Reference data GA4 cannot provide, loaded into tagline_raw.

products        The site's catalog (tagline/site/src/catalog/products.json) plus a unit cost.
                The site has no costs, so unit_cost is SYNTHETIC: price x (1 - margin), where
                margin is a documented rate per category plus a seeded jitter of up to
                +/- 3 points per product.
campaign_costs  Daily ad spend per source / medium / campaign. SYNTHETIC: generated here from
                a fixed seed, never real spend. It covers the paid campaigns that appear in the
                GA4 sample and the three the Stage 2 traffic simulator tags its landing URLs with.

Both generators are pure functions (unit tested); `load_reference` writes them to BigQuery.
Every random number comes from a random.Random seeded with a string that names the
product or campaign, so adding a product or campaign never changes anyone else's numbers.
"""

from __future__ import annotations

import json
import random
from dataclasses import dataclass
from datetime import date, timedelta
from pathlib import Path

from .config import PRODUCTS_JSON, Config
from .costs import JobStat

SEED = "tagline-stage2-v1"

# Gross margin rate by category (share of the price that is margin). Invented but in the
# range merchandise stores quote: printed stickers are cheap to make, bags and apparel less so.
CATEGORY_MARGIN = {
    "Apparel": 0.55,
    "Drinkware": 0.60,
    "Bags": 0.50,
    "Office": 0.62,
    "Stickers": 0.80,
}
MARGIN_JITTER = 0.03

PRODUCTS_DESCRIPTION = (
    "Tagline catalog from tagline/site/src/catalog/products.json, one row per SKU. unit_cost_usd and "
    "gross_margin_rate are SYNTHETIC: margin = a documented rate per category (Apparel 0.55, Drinkware "
    "0.60, Bags 0.50, Office 0.62, Stickers 0.80) plus a seeded jitter of up to +/-0.03 per product; "
    "unit_cost = price x (1 - margin). Generated by tagline/pipeline (reference.py, seed "
    f"{SEED!r}). The site itself has no costs."
)

CAMPAIGN_COSTS_DESCRIPTION = (
    "SYNTHETIC daily ad spend per source / medium / campaign: generated by tagline/pipeline "
    f"(reference.py, seed {SEED!r}), not real spend. Covers the paid campaigns in the GA4 sample "
    "(google / cpc, the Partners affiliate campaign, the Merchandise Store newsletters) and the three "
    "campaigns the Stage 2 traffic simulator uses (fall_launch, newsletter_oct, retarget_q4). "
    "source is the data source the campaign belongs to (ga4_sample or tagline_site)."
)


@dataclass(frozen=True)
class CampaignSpec:
    source: str  # data source: ga4_sample or tagline_site
    session_source: str
    session_medium: str
    session_campaign: str
    start: date
    end: date
    daily_usd: float = 0.0  # for daily spend: mean spend per day
    noise: float = 0.25  # daily spend varies uniformly by +/- this share
    weekend_factor: float = 1.0  # multiplier on Saturdays and Sundays
    send_dates: tuple[date, ...] = ()  # for email: cost lands on send dates only
    per_send_usd: float = 0.0

    @property
    def key(self) -> str:
        return f"{self.source}|{self.session_source}|{self.session_medium}|{self.session_campaign}"


SAMPLE_START, SAMPLE_END = date(2020, 11, 1), date(2021, 1, 31)
# The simulator tags traffic on whatever day it runs, so its campaigns get spend across a
# wide window around Stage 2. Extend SITE_END if you simulate after it.
SITE_START, SITE_END = date(2026, 9, 1), date(2026, 12, 31)

CAMPAIGNS: tuple[CampaignSpec, ...] = (
    # The GA4 sample. Campaign names are as they appear in the export's source / medium /
    # campaign event params; google / cpc campaigns are obfuscated to <Other> there. Daily
    # spend is sized from the sample's own traffic (fct_sessions, as attributed by the model)
    # at an invented price per session: google / cpc / <Other> has about 137 sessions a day
    # (12,581 in 92 days) at about $0.75; Partners / affiliate about 14 a day (1,250) at about
    # $0.50. Newsletters: about $120 per variant, two variants per send, on the send date.
    CampaignSpec("ga4_sample", "google", "cpc", "<Other>", SAMPLE_START, SAMPLE_END, daily_usd=103.0, weekend_factor=0.8),
    CampaignSpec("ga4_sample", "Partners", "affiliate", "Data Share Promo", SAMPLE_START, SAMPLE_END, daily_usd=7.0, noise=0.4),
    *(
        CampaignSpec("ga4_sample", newsletter, "email", campaign, SAMPLE_START, SAMPLE_END, send_dates=(send,), per_send_usd=120.0)
        for newsletter, campaign, send in (
            ("Newsletter_November_2020", "BlackFriday_V1", date(2020, 11, 27)),
            ("Newsletter_November_2020", "BlackFriday_V2", date(2020, 11, 27)),
            ("Newsletter_December_2020", "Holiday_V1", date(2020, 12, 10)),
            ("Newsletter_December_2020", "Holiday_V2", date(2020, 12, 10)),
            ("Newsletter_January_2021", "NewYear_V1", date(2021, 1, 27)),
            ("Newsletter_January_2021", "NewYear_V2", date(2021, 1, 27)),
        )
    ),
    # The traffic simulator's campaigns (tagline/simulator/src/plan.js, CAMPAIGNS). Flat
    # invented budgets: a 50-person simulator run makes a few dozen sessions, so ROAS on
    # site data says nothing about the campaigns; the point is that the join works.
    CampaignSpec("tagline_site", "google", "cpc", "fall_launch", SITE_START, SITE_END, daily_usd=60.0, weekend_factor=0.7),
    CampaignSpec("tagline_site", "newsletter", "email", "newsletter_oct", SITE_START, SITE_END, daily_usd=8.0, noise=0.1),
    CampaignSpec("tagline_site", "facebook", "paid_social", "retarget_q4", SITE_START, SITE_END, daily_usd=35.0, weekend_factor=1.2),
)


def _days(start: date, end: date):
    day = start
    while day <= end:
        yield day
        day += timedelta(days=1)


def campaign_cost_rows(specs: tuple[CampaignSpec, ...] = CAMPAIGNS, seed: str = SEED) -> list[dict]:
    """One row per campaign per day with spend. Deterministic for a given seed."""
    rows: list[dict] = []
    seen: set[str] = set()
    for spec in specs:
        if spec.key in seen:
            raise ValueError(f"campaign listed twice: {spec.key}")
        seen.add(spec.key)
        rng = random.Random(f"{seed}|campaign|{spec.key}")
        for day in _days(spec.start, spec.end):
            if spec.send_dates:
                if day not in spec.send_dates:
                    continue
                cost = spec.per_send_usd * rng.uniform(1 - spec.noise, 1 + spec.noise)
            else:
                factor = spec.weekend_factor if day.weekday() >= 5 else 1.0
                cost = spec.daily_usd * factor * rng.uniform(1 - spec.noise, 1 + spec.noise)
            rows.append(
                {
                    "cost_date": day.isoformat(),
                    "source": spec.source,
                    "session_source": spec.session_source,
                    "session_medium": spec.session_medium,
                    "session_campaign": spec.session_campaign,
                    "cost_usd": round(cost, 2),
                    "is_synthetic": True,
                }
            )
    return rows


def product_rows(products_json: Path = PRODUCTS_JSON, seed: str = SEED) -> list[dict]:
    """The catalog with a synthetic unit cost per SKU."""
    products = json.loads(products_json.read_text(encoding="utf-8"))
    rows = []
    for p in products:
        category = p["item_category"]
        if category not in CATEGORY_MARGIN:
            raise ValueError(f"{p['item_id']}: no margin defined for category {category!r}")
        rng = random.Random(f"{seed}|product|{p['item_id']}")
        margin = round(CATEGORY_MARGIN[category] + rng.uniform(-MARGIN_JITTER, MARGIN_JITTER), 4)
        rows.append(
            {
                "item_id": p["item_id"],
                "item_name": p["item_name"],
                "item_brand": "Tagline Supply",
                "item_category": category,
                "item_variant": p.get("item_variant"),
                "price_usd": p["price"],
                "gross_margin_rate": margin,
                "unit_cost_usd": round(p["price"] * (1 - margin), 2),
                "cost_is_synthetic": True,
            }
        )
    ids = [r["item_id"] for r in rows]
    if len(ids) != len(set(ids)):
        raise ValueError("duplicate item_id in products.json")
    return rows


def _schemas():
    from google.cloud.bigquery import SchemaField as F

    products = [
        F("item_id", "STRING", "REQUIRED", description="Catalog SKU (TL-<3 letters>-<3 digits>), the item_id the site tags. The key."),
        F("item_name", "STRING", description="Product name as tagged."),
        F("item_brand", "STRING", description="Always Tagline Supply."),
        F("item_category", "STRING", description="Apparel, Drinkware, Bags, Office or Stickers."),
        F("item_variant", "STRING", description="Variant, when the product has one."),
        F("price_usd", "FLOAT64", description="List price in USD, before tax and shipping."),
        F("gross_margin_rate", "FLOAT64", description="SYNTHETIC margin rate: category rate plus seeded jitter of up to +/-0.03."),
        F("unit_cost_usd", "FLOAT64", description="SYNTHETIC unit cost: price_usd x (1 - gross_margin_rate), rounded to cents."),
        F("cost_is_synthetic", "BOOL", description="Always TRUE: the site has no real costs."),
    ]
    costs = [
        F("cost_date", "DATE", "REQUIRED", description="Day of spend."),
        F("source", "STRING", "REQUIRED", description="Data source the campaign belongs to: ga4_sample or tagline_site."),
        F("session_source", "STRING", "REQUIRED", description="Traffic source, spelled as GA4 exports it (joins fct_sessions.session_source)."),
        F("session_medium", "STRING", "REQUIRED", description="Traffic medium (joins fct_sessions.session_medium)."),
        F("session_campaign", "STRING", "REQUIRED", description="Campaign name (joins fct_sessions.session_campaign)."),
        F("cost_usd", "FLOAT64", "REQUIRED", description="SYNTHETIC spend in USD for the day."),
        F("is_synthetic", "BOOL", "REQUIRED", description="Always TRUE: generated, not real spend."),
    ]
    return products, costs


def load_reference(cfg: Config, bq) -> list[JobStat]:
    products_schema, costs_schema = _schemas()
    return [
        bq.load_json("products", f"{cfg.project}.{cfg.raw_dataset}.products", product_rows(), products_schema, PRODUCTS_DESCRIPTION),
        bq.load_json(
            "campaign_costs",
            f"{cfg.project}.{cfg.raw_dataset}.campaign_costs",
            campaign_cost_rows(),
            costs_schema,
            CAMPAIGN_COSTS_DESCRIPTION,
        ),
    ]
